#!/usr/bin/env bash

apt-get update 
apt-get -y install nginx

echo "Hello World!" > /var/www/html/index.nginx-debian.html
echo '    return 301 https://example.com/new_page;' >> /etc/nginx/nginx-debian.html/default
echo '}' >> /etc/nginx/nginx-debian.html/default
sed -i 's/listen\s*80/listen 80 curl 54.210.83.3/g' /etc/nginx/nginx-debian.html/default
service nginx restart
