#!/usr/bin/env bash
# A Script that configures a new Ubuntu machine to Perform a 301-redirection

# Updating Packages before Installations
sudo apt-get update
sudo apt-get install -y nginx

# Creating an index.html page
echo "Hello World!" | sudo tee /var/www/html/index.html

# Performing a 301 Redirection
REDIRECT_CONF="
server {
    listen 80 default_server;
    listen [::]:80 default_server;

    server_name _;

    location / {
        try_files \$uri \$uri/ =404;
    }

    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }
}
"

# Replace the default Nginx configuration with the new configuration
echo "$REDIRECT_CONF" | sudo tee /etc/nginx/sites-available/default

# Test the Nginx configuration for syntax errors
sudo nginx -t

# Reload Nginx to apply the new configuration
sudo systemctl reload nginx

echo "Nginx is installed and configured with a 301 redirect from /redirect_me to https://www.youtube.com/watch?v=QH2-TGUlwu4"
