#!/usr/bin/env bash
# configures a new HAproxy as a load balancer

# Install HAproxy on a server
apt-get -y update
apt-get -y install haproxy=1.6.\*

# Configure haproxy configuration file to distribute requests using a roundrobin algorithm
echo '
frontend detola3.tech
        bind 0:80
        default_backend web_servers

backend web_servers
        balance roundrobin
        server 156689-web-01 54.87.207.98
        server 156689-web-02 52.0.5.134
' >> /etc/haproxy/haproxy.cfg

# Restart HAproxy service
service haproxy restart
