#!/usr/bin/env bash

# Install nginx if not already installed
apt-get -y update
apt-get -y install nginx

# Start nginx service
service nginx start

# Check if Nginx is running
if service nginx status | grep -q "active (running)"; then
    echo "Nginx is running."
else
    echo "Nginx is not running."
fi
