#!/usr/bin/env bash
# using ssh to connect to a server

# Server details
username="ubuntu"
ip="100.26.231.131"
private_key="~/.ssh/school"

# Use ssh with single-character flags
ssh -i "$private_key" "$username@$ip"
